### PR TITLE
Initial attempt to fix numbering

### PR DESCRIPTION
**Pull request by AdityaGarg8**

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
Preview on GitHub shows correct numbering but on wiki after step 6 it changes to 1.

**Comment by AdityaGarg8** [comment]
I guess the only way out to check this is to merge this

**Comment by Redecorating** [comment]
I think the issue may be that  you are using 3 spaces to indent the things in each dot point. In the hybrid graphics page, the numbering is fine and I think that's because it uses 4 spaces,

**Comment by AdityaGarg8** [comment]
Let me do it to 4

**Comment by AdityaGarg8** [comment]
It's fixed now

**Pull request merged**
