### PR TITLE
Manjaro Wiki Files

### PR DESCRIPTION
**Pull request by JPyke3**
These are all the files in the existing Manjaro wiki.

### CODE REVIEW

**Comment by JPyke3** [comment]
@networkException any chance you would be able to lint these files? No rush :)

**Comment by networkException** [comment]
sure

**Comment by networkException** [comment]
could you enable push access for me on your branch?

**Comment by JPyke3** [comment]
It's been enabled the whole time 👍

**Comment by networkException** [comment]
that is weird, I don't seem to have permission

image

**Comment by networkException** [comment]
Turns out that pushing doesn't work when having the pr branch checked out

**Pull request merged**
