### PR TITLE
iGPU: Remove MBP 16,4 Instructions

### PR DESCRIPTION
**Pull request by AdityaGarg8**
A patch to support the GPU is now available.

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
@NoaHimesaka1873 @sharpenedblade please mention when you've added support to the distros you are maintaining.

**Comment by NoaHimesaka1873** [comment]
@AdityaGarg8 Is it in linux-t2-patches repo? Then, it will be included in 6.6.8 and 6.1.69.

**Comment by AdityaGarg8** [comment]
It has been added yesterday

**Comment by sharpenedblade** [comment]
> @NoaHimesaka1873 @sharpenedblade please mention when you've added support to the distros you are maintaining.

I pushed the change, it should be built in a few hours

**Pull request merged**
