### PR TITLE
Arch: Update installation guide

### PR DESCRIPTION
**Pull request by AdityaGarg8**
I found some errors when trying to install Arch, so correcting them

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
Add apple-bce to the MODULES list in /etc/mkinitcpio.conf, and then run mkinitcpio -P

this step doesn't seem to be necessary. In fact it was causing panics for me.

**Review by Redecorating — APPROVED** [review]
I haven't tested this but it makes sense to me.

**Comment by Redecorating** [comment]
> Add apple-bce to the MODULES list in /etc/mkinitcpio.conf, and then run mkinitcpio -P
> 
> this step doesn't seem to be necessary. In fact it was causing panics for me.

hmm this is for if you want apple-bce to be loaded before the root partition mounts (eg if its encrypted and you need to type the password). Do you have a copy of the kernel panic log?

**Comment by AdityaGarg8** [comment]
> > Add apple-bce to the MODULES list in /etc/mkinitcpio.conf, and then run mkinitcpio -P
> > this step doesn't seem to be necessary. In fact it was causing panics for me.
> 
> hmm this is for if you want apple-bce to be loaded before the root partition mounts (eg if its encrypted and you need to type the password). Do you have a copy of the kernel panic log?

Nope. I've removed Arch 😞. Still, I don't find this very necessary. If you want, I can keep this

**Comment by Redecorating** [comment]
> > > Add apple-bce to the MODULES list in /etc/mkinitcpio.conf, and then run mkinitcpio -P
> > > this step doesn't seem to be necessary. In fact it was causing panics for me.
> > 
> > 
> > hmm this is for if you want apple-bce to be loaded before the root partition mounts (eg if its encrypted and you need to type the password). Do you have a copy of the kernel panic log?
> 
> Nope. I've removed Arch 😞. Still, I don't find this very necessary. If you want, I can keep this

It doesn't cause issues for me so maybe we can keep it for the time being.

**Pull request merged**
