### PR TITLE
Tools: use apple-touchbar instead of apple-ib-tb

### PR DESCRIPTION
**Pull request by AdityaGarg8**

### CODE REVIEW

**Comment by networkException** [comment]
Has the name change shipped in all kernels?

**Comment by Redecorating** [comment]
https://github.com/Redecorating/linux-t2-arch/tree/touchbar should have those changes for arch, i'll test after the ci compiles and then probably put that in the 6.0.9-1 release (which is in arch testing repos so should be soon)

**Comment by AdityaGarg8** [comment]
I guess the maintainers could give a green signal whenever they update the kernels of their distro by commenting it here. Once all have done, some wiki maintainer could merge this.

**Comment by AdityaGarg8** [comment]
I guess we've got the new driver on Arch as well.

@kekry, is the script used on nixOS?

On fedora I guess suspend anyways was broken.

@NoaHimesaka1873 , any updates on EOS and Manjaro?

**Comment by NoaHimesaka1873** [comment]
> I guess we've got the new driver on Arch as well.
> 
> 
> 
> @kekrby, is the script used on nixOS?
> 
> 
> 
> On fedora I guess suspend anyways was broken.
> 
> 
> 
> @NoaHimesaka1873 , any updates on EOS and Manjaro?

Not yet. It will be incorportated into Arch Xanmod and Manjaro in 6.1.

**Comment by kekrby** [comment]
> @kekrby, is the script used on nixOS?

Yes, the suspend script is used in NixOS.

I updated the kernel of NixOS by the way.

**Comment by AdityaGarg8** [comment]
Even Fedora got an update today.

I guess we can merge it then?

**Pull request merged**
