### PR TITLE
Fan: Use the rust daemon

### PR DESCRIPTION
**Pull request by AdityaGarg8**

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
@sharpenedblade , I need fedora instructions

**Comment by sharpenedblade** [comment]
```
sudo dnf install t2fanrd
sudo systemctl enable --now t2fanrd
```

**Comment by sharpenedblade** [comment]
I think the PR is ready to be merged if you add the fedora instructions. Can you also add that `t2fanrd` is installed by default on Fedora.

**Review by sharpenedblade — APPROVED** [review]

**Comment by AdityaGarg8** [comment]
Could you also add instructions/link the page to add the repo containing the daemon as well @sharpenedblade. Its for the users who use some other Fedora based distro.

**Comment by AdityaGarg8** [comment]
Also, you can PR to the fan branch of this repo for instructions

**Comment by sharpenedblade** [comment]
https://github.com/t2linux/wiki/pull/496

**Pull request merged**
