### PR TITLE
Update audio-config.md for Pipewire distributions (now working!)

### PR DESCRIPTION
**Pull request by nikodunk**

### CODE REVIEW

**Comment by nikodunk** [comment]
Hi there,

Finally got this working today. Let me know if you have any questions.

Best,
Niko

**Review by networkException — CHANGES_REQUESTED** [review]
Please fixup the linting errors

**Comment by nikodunk** [comment]
Yeah sorry committed this  all on gh editor hehe.

**Review by Redecorating — APPROVED** [review]

**Review by networkException — APPROVED** [review]

**Comment by nikodunk** [comment]
Thanks team!

**Comment by networkException** [comment]
oop, forgot to merge

**Pull request merged**
