### PR TITLE
Fixed formatting of Gentoo guide

### PR DESCRIPTION
**Pull request by EmreTech**
Didn't think this would happen I'm sorry 😖

### CODE REVIEW

**Comment by AdityaGarg8** [comment]
Though it's merged now, I still have some doubts.

**Comment by AdityaGarg8** [comment]
Firstly, we can use disk utility to partition the SSD. Why use Bootcamp?

**Comment by AdityaGarg8** [comment]
Infact bootcamp starts partitioning after getting path of the Windows ISO iirc.

**Comment by AdityaGarg8** [comment]
Secondly, talking about the patches, the additional patch mentioned for kernels below 5.16 is the EFI one which you have included in the mainline patches (Redecorating's fork), then why specially mentioned that one?

**Comment by AdityaGarg8** [comment]
Lastly, the source of kernel being compiled is lastest from kernel.org, or the ones supplied by gentoo?

**Comment by Redecorating** [comment]
> Firstly, we can use disk utility to partition the SSD. Why use Bootcamp?

The introduced guide uses bootcamp assistant to clear snapshots and make space on the macOS apfs partition, so it can then be partitioned with Disk Utility. Bootcamp Assistant itself isn't doing the partitioning.

> Secondly, talking about the patches, the additional patch mentioned for kernels below 5.16 is the EFI one which you have included in the mainline patches (Redecorating's fork), then why specially mentioned that one?

Gentoo is still on 5.15, and if they checkout a 5.15 tag on my fork then it'll not have the efi patch. Adding in that patch means they don't have to mess around with efi=noruntime or mounting efivarfs ro

**Comment by AdityaGarg8** [comment]
Right
Thanks

**Comment by EmreTech** [comment]
> Secondly, talking about the patches, the additional patch mentioned for kernels below 5.16 is the EFI one which you have included in the mainline patches (Redecorating's fork), then why specially mentioned that one?

It's a replacement for making efivars unwritable (suggested by Redecorating themselves)

**Comment by EmreTech** [comment]
> Lastly, the source of kernel being compiled is latest from kernel.org, or the ones supplied by gentoo?

It's provided from Gentoo, the package name is "gentoo-sources". It doesn't have the latest kernel yet, but it has some patches to the kernel that improve security and stuff.

**Pull request merged**
