### PR TITLE
Added back alternate Ubuntu repo

### PR DESCRIPTION
**Pull request by AdityaGarg8**
I am adding this back cause I am now able to get some time to maintain this. Also, it has the 5.10 kernels which are not there in the other marcosfad’s repo.

### CODE REVIEW

**Review by Redecorating — CHANGES_REQUESTED** [review]
Can you mention why people would need the kernel from your repo (i.e. for bluetooth on 16,1)?

**Comment by networkException** [comment]
Also alternative link sounds like it's a mirror rather than a separately maintained fork

**Comment by AdityaGarg8** [comment]
Apart from Bluetooth what should I add?

**Comment by AdityaGarg8** [comment]
I guess you may add updated faster, but practically depends on my schedule

**Comment by AdityaGarg8** [comment]
As in I have got a whole week free

**Comment by AdityaGarg8** [comment]
Should I faster?

**Review by Redecorating — APPROVED** [review]

**Pull request merged**
