### PR TITLE
Update wifi.md

### PR DESCRIPTION
**Pull request by AdityaGarg8**
Marcosfad's repo now supports bcm4377

### CODE REVIEW

**Comment by networkException** [comment]
marcosfad is updating the naming of all kernel releases, can you use this pr to update any references to the ubuntu kernels? (I'm unsure if the currently released ones / the running actions reflect all changes, its probably best to ask them to be sure; I can also work on this if you prefer, I'd close the pr in that case tho as I don't like to review 10 single ones)

**Comment by AdityaGarg8** [comment]
I'll check out later today.

**Comment by AdityaGarg8** [comment]
Check out now.

**Comment by AdityaGarg8** [comment]
@networkException , please review it now.

**Pull request merged**
